ALTER TABLE tasks ALTER COLUMN priority DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN priority SET DEFAULT NULL;
ALTER TABLE tasks ALTER COLUMN progress DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN progress SET DEFAULT NULL;
